### ISSUE TITLE
Road map toward a full package

### ISSUE THREAD

**Issue by zhentaoshi** [chenyang45/BoostedHP#2]
I have a few thoughts about how to develop the package into a full-fledged one. Now we only have a skeleton.

* Make the output list of the main function as an R object with a name, say `bHP`
* Require the input `x` be a `ts` object, so that we can keep the time series information and attach it onto the returned cycle and residual
* R runs on many generic methods, for example `plot` and `residuals`. In our case, we can use
    - `residuals` to extract the cyclical component
    - `predict` to extract the trend component
    - `plot` to display the graph of the raw time series and the estimated trend
    - Is there some method called `information criterion` or something that is used to track the path of the p-value of ADF or the value of BIC?

**Comment by chenyang45** [comment]
thank you very much!

**Comment by chenyang45** [comment]
you mean that we need to record the path of the p-value of ADF or the value of BIC and print it out as one of the output?

**Comment by zhentaoshi** [comment]
We have had the path as `adf_hist` and `BIC_hist`. We just need to use a method to extract it.
