### ISSUE TITLE
bHP crashes with R 4.2.2

### ISSUE THREAD

**Issue by giannilmbd** [chenyang45/BoostedHP#6]
Hi,
Thanks for making this code available.
I've been using this code a few times with older versions of R. I just upgraded to R 4.2.2 (on Ubuntu 22.04) and it crashes (R needs to restart) without leaving any message. 

Is this problem known? 

Cheers
Gianni

**Comment by zhentaoshi** [comment]
Our main repo is now moved to https://github.com/zhentaoshi/bHP_R_pkg with the latest version. Could you please try the latest version? If the problem remains, please leave a message there and we will inspect it. Thank you.

**Comment by giannilmbd** [comment]
Excellent. Thanks. I'll try that version
Cheers

**Comment by giannilmbd** [comment]
Hi,
On my machine the attached example crashes R (segmentation fault) if the
length of the series is somewhat above 150 (didn't use to happen some
months ago) and doesn't happen on a different machine.

One suspicion is that on the machine that crashes I've installed a number
of Intel libraries that might mess-up with the compilation of your code.

Any idea?
Cheers
Gianni

fr_=12
tmp25<-as.ts(rnorm(170))
lmb<-1600 *(fr_/4)^4 # Ravn and Uhlig 2002
out<-mFilter::mFilter(
  tmp25
  ,filter='HP',lambda=lmb,na.rm=T)
out<-BoostedHP(tmp25,lambda = lmb,iter = T)

**Comment by shenshuuu** [comment]
This is a specific problem that cannot be repeated from our side. These codes work fine on our machine.

**Comment by zhentaoshi** [comment]
Dear Gianni, we ran your code example and it worked with no error. I believe this issue is specific. Could you please check your configuration? We're sorry that we cannot help without replicability.
